In [166]:
import pandas as pd

In [167]:
WorldCupMatches = pd.read_csv(r'C:\Users\Joaco\OneDrive\Documentos\Joaquin\Cursos\Proyecto BA\Proyectos\FIFA-WorldCup-Analysis\data\raw\WorldCupMatches.csv', encoding='latin-1')
WorldCupPlayers = pd.read_csv(r'C:\Users\Joaco\OneDrive\Documentos\Joaquin\Cursos\Proyecto BA\Proyectos\FIFA-WorldCup-Analysis\data\raw\WorldCupPlayers.csv', encoding='latin-1')
WorldCups = pd.read_csv(r'C:\Users\Joaco\OneDrive\Documentos\Joaquin\Cursos\Proyecto BA\Proyectos\FIFA-WorldCup-Analysis\data\raw\WorldCups.csv', encoding='latin-1')

In [168]:
print(f'La cantidad total de datos y columna es de {WorldCupMatches.shape}')

La cantidad total de datos y columna es de (852, 20)

In [169]:
print(f'La cantidad total de datos y columna es de {WorldCupPlayers.shape}')

La cantidad total de datos y columna es de (37784, 9)

In [170]:
print(f'La cantidad total de datos y columna es de {WorldCups.shape}')

La cantidad total de datos y columna es de (20, 10)

In [171]:
WorldCupMatches.head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444.0,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX
1,1930,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,18346.0,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059.0,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA

In [172]:
WorldCupPlayers.head()

,RoundID,MatchID,Team Initials,Coach Name,Line-up,Shirt Number,Player Name,Position,Event
0,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Alex THEPOT,GK,NaN
1,201,1096,MEX,LUQUE Juan (MEX),S,0,Oscar BONFIGLIO,GK,NaN
2,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Marcel LANGILLER,NaN,G40'
3,201,1096,MEX,LUQUE Juan (MEX),S,0,Juan CARRENO,NaN,G70'
4,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Ernest LIBERATI,NaN,NaN

In [173]:
WorldCups.head()

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance
0,1930,Uruguay,Uruguay,Argentina,USA,Yugoslavia,70,13,18,590.549
1,1934,Italy,Italy,Czechoslovakia,Germany,Austria,70,16,17,363
2,1938,France,Italy,Hungary,Brazil,Sweden,84,15,18,375.7
3,1950,Brazil,Uruguay,Brazil,Sweden,Spain,88,13,22,1.045.246
4,1954,Switzerland,Germany FR,Hungary,Austria,Uruguay,140,16,26,768.607

Observado si hay nulos

In [174]:
WorldCupMatches.isnull().sum()

Year                    0
Datetime                0
Stage                   0
Stadium                 0
City                    0
Home Team Name          0
Home Team Goals         0
Away Team Goals         0
Away Team Name          0
Win conditions          0
Attendance              2
Half-time Home Goals    0
Half-time Away Goals    0
Referee                 0
Assistant 1             0
Assistant 2             0
RoundID                 0
MatchID                 0
Home Team Initials      0
Away Team Initials      0
dtype: int64

In [175]:
WorldCupPlayers.isnull().sum()

RoundID              0
MatchID              0
Team Initials        0
Coach Name           0
Line-up              0
Shirt Number         0
Player Name          0
Position         33641
Event            28715
dtype: int64

In [176]:
WorldCups.isnull().sum()

Year              0
Country           0
Winner            0
Runners-Up        0
Third             0
Fourth            0
GoalsScored       0
QualifiedTeams    0
MatchesPlayed     0
Attendance        0
dtype: int64

Obserrvando si hay duplicados

In [177]:
WorldCupMatches.duplicated().sum()

np.int64(16)

In [178]:
WorldCupPlayers.duplicated().sum()

np.int64(736)

In [179]:
WorldCups.duplicated().sum()

np.int64(0)

Revisión de Tipos (Dtypes)

In [180]:
WorldCupMatches.dtypes

Year                      int64
Datetime                 object
Stage                    object
Stadium                  object
City                     object
Home Team Name           object
Home Team Goals           int64
Away Team Goals           int64
Away Team Name           object
Win conditions           object
Attendance              float64
Half-time Home Goals      int64
Half-time Away Goals      int64
Referee                  object
Assistant 1              object
Assistant 2              object
RoundID                   int64
MatchID                   int64
Home Team Initials       object
Away Team Initials       object
dtype: object

In [181]:
WorldCupPlayers.dtypes

RoundID           int64
MatchID           int64
Team Initials    object
Coach Name       object
Line-up          object
Shirt Number      int64
Player Name      object
Position         object
Event            object
dtype: object

In [182]:
WorldCups.dtypes

Year               int64
Country           object
Winner            object
Runners-Up        object
Third             object
Fourth            object
GoalsScored        int64
QualifiedTeams     int64
MatchesPlayed      int64
Attendance        object
dtype: object

Eliminar filas vacías

In [183]:
# Para que elimine las filas que todos los campos sean null
WorldCupMatches.dropna(how='all', inplace=True)
WorldCupPlayers.dropna(how='all', inplace=True)
WorldCups.dropna(how='all', inplace=True)

Eliminando duplicados

In [184]:
duplicados_antes_matches = WorldCupMatches.duplicated(subset='MatchID').sum()
print(f"Total valores duplicas = {duplicados_antes_matches}")
#Boramos los valores duplicados de la tabla matches 
WorldCupMatches.drop_duplicates(subset='MatchID', inplace=True)

Total valores duplicas = 16

In [185]:
WorldCupMatches.duplicated().sum()

np.int64(0)

In [186]:

duplicados_antes_players = WorldCupPlayers.duplicated().sum()
print(f"Total valores duplicas = {duplicados_antes_players}")
#Boramos los valores duplicados de la tabla matches 
WorldCupPlayers.drop_duplicates(subset=['MatchID', 'Player Name'],keep='first' ,inplace=True)

Total valores duplicas = 736

In [187]:
WorldCupPlayers.duplicated().sum()

np.int64(0)

Estandarizacion de datos

In [188]:
nombres_paises_estandarizados = {
    
    'Germany FR' : 'Germany',
    'German DR' : 'Germany',
    'Soviet Union' : 'Russia',
    'Korea Republic' : 'South Korea',
    'Korea DPR' : 'North Korea ',
    'rn">United Arab Emirates' : 'United Arab Emirates',
    'rn">Republic of Ireland' : 'Republic of Ireland',
    "Cï¿½te d'Ivoire" : "Ivory Coast",
    'rn">Bosnia and Herzegovina' : 'Bosnia and Herzegovina',
    'rn">Trinidad and Tobago' : 'Trinidad and Tobago',
    'rn">Serbia and Montenegro' : 'Serbia and Montenegro'
    
}

WorldCupMatches['Home Team Name'] = WorldCupMatches['Home Team Name'].replace(nombres_paises_estandarizados)
WorldCupMatches['Away Team Name'] = WorldCupMatches['Away Team Name'].replace(nombres_paises_estandarizados)
WorldCups['Winner'] = WorldCups['Winner'].replace(nombres_paises_estandarizados)
WorldCups['Runners-Up'] = WorldCups['Runners-Up'].replace(nombres_paises_estandarizados)
WorldCups['Third'] = WorldCups['Third'].replace(nombres_paises_estandarizados)
WorldCups['Fourth'] = WorldCups['Fourth'].replace(nombres_paises_estandarizados)

In [189]:
Iniciales_paises_estandarizados = {
    'FRG' : 'GER',
    'GDR' : 'GER',
    'URS' : 'RUS',
}

WorldCupPlayers['Team Initials'] = WorldCupPlayers['Team Initials'].replace(Iniciales_paises_estandarizados)
WorldCupMatches['Home Team Initials'] = WorldCupMatches['Home Team Initials'].replace(Iniciales_paises_estandarizados) 
WorldCupMatches['Away Team Initials'] = WorldCupMatches['Away Team Initials'].replace(Iniciales_paises_estandarizados)

In [190]:
# Elimiando los puntos que tenian nuestras cantidades de attendance
WorldCups['Attendance'] = WorldCups['Attendance'].str.replace(".","",regex=False).astype(int)

In [191]:
nombre_estadios_estandarizados = {
    'Stade Vï¿½lodrome' : 'Stade Vélodrome',
    'Maracanï¿½ - Estï¿½dio Jornalista Mï¿½rio Filho' :'Maracanã - Estádio Jornalista Mário Filho' ,
    'Nou Camp - Estadio Leï¿½n' : 'Nou Camp - Estadio León',
    'Estadio Josï¿½ Marï¿½a Minella' : 'Estadio José María Minella',
    'Estadio Olï¿½mpico Chateau Carreras' : 'Estadio Olímpico Chateau Carreras',
    'Estadio Municipal de Balaï¿½dos' : 'Estadio Municipal de Balaídos',
    'Estadio Olï¿½mpico Universitario' : 'Estadio Olímpico Universitario',
}

WorldCupMatches['Stadium'] = WorldCupMatches['Stadium'].replace(nombre_estadios_estandarizados)

Formateo para SQL

In [192]:

# Quitar espacios vacíos 
WorldCupMatches['Datetime'] = WorldCupMatches['Datetime'].str.strip()

#Conversión a Objeto Fecha 

WorldCupMatches['Datetime'] = pd.to_datetime(WorldCupMatches['Datetime'], format='%d %b %Y - %H:%M', errors='coerce')

#  Formateo final para el CSV 
# Una vez que ya es fecha, la volvemos texto con el formato que MySQL 
WorldCupMatches['Datetime'] = WorldCupMatches['Datetime'].dt.strftime('%Y-%m-%d %H:%M:%S')


nulos = WorldCupMatches['Datetime'].isna().sum()

In [193]:
nulos

np.int64(10)

In [194]:
# Quita espacios al inicio y final y "saltos de línea" que suelen dar problemas en SQL
WorldCupMatches = WorldCupMatches.map(lambda x: x.strip() if isinstance(x, str) else x)
WorldCupPlayers = WorldCupPlayers.map(lambda x: x.strip() if isinstance(x, str) else x)
WorldCups = WorldCups.map((lambda x: x.strip() if isinstance(x, str) else x))

In [195]:
#Cambiando el nombre de mis columnas quitando espacion y guiones en medio para que sean sustituidos por guiones bajos
WorldCupMatches.columns = [col.lower().replace(' ', '_').replace('-','_') for col in WorldCupMatches.columns]
WorldCupPlayers.columns = [col.lower().replace(' ', '_').replace('-','_') for col in WorldCupPlayers.columns]
WorldCups.columns = [col.lower().replace(' ', '_').replace('-','_') for col in WorldCups.columns]

In [196]:
WorldCupMatches.head()

,year,datetime,stage,stadium,city,home_team_name,home_team_goals,away_team_goals,away_team_name,win_conditions,attendance,half_time_home_goals,half_time_away_goals,referee,assistant_1,assistant_2,roundid,matchid,home_team_initials,away_team_initials
0,1930,1930-07-13 15:00:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444.0,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX
1,1930,1930-07-13 15:00:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,18346.0,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL
2,1930,1930-07-14 12:45:00,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059.0,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,1930-07-14 14:50:00,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,1930-07-15 16:00:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA

Importar mis tablas

In [197]:
import csv 

ruta_salida = r'C:\Users\Joaco\OneDrive\Documentos\Joaquin\Cursos\Proyecto BA\Proyectos\FIFA-WorldCup-Analysis\data\processed\\'

WorldCupMatches.to_csv(ruta_salida + 'WorldCupMatches.csv',index=False,quoting=csv.QUOTE_ALL,encoding='utf-8')
WorldCupPlayers.to_csv(ruta_salida + 'WorldCupPlayers.csv',index=False,quoting=csv.QUOTE_ALL,encoding='utf-8')
WorldCups.to_csv(ruta_salida + 'WorldCups.csv',index=False,quoting=csv.QUOTE_ALL,encoding='utf-8')

In [198]:
WorldCupPlayers.shape

(37021, 9)